# -*- coding: utf-8 -*-
# <nbformat>3.0</nbformat>

# <markdowncell>

# Traverse.py Muti-Collection Analysis
# ====================================
# 
# In this notebook, we will be performing analyses on a number of comma-separated values files generated by `traverse.py`.
# 
# ### First, grab the csv files from my Git repo.
# 
# All of the CSV data files are stored on my GitHub repository at http://github.com/hawkw/traverse, in the `data/` directory. The `data/datafiles.csv` file contains a listing of the available datafiles (as well as some additional metadata). We're going to use the paths stored in that file to access the individual data files.

# <codecell>

import io, urllib2, bz2, pandas

# Get the metadata CSV that contains the listing of all runs
csvData = pandas.read_csv('https://raw.github.com/hawkw/traverse/master/data/datafiles.csv') 

datafiles = {}

# Loop through the filenames column and grab each filename.
for filename in csvData['Filename']:
    
    url = 'https://raw.github.com/hawkw/traverse/master/data/' + filename
    
    try:
        response = urllib2.urlopen(url).read()
    except Exception as e:
        print ("Caught HTTPError while accessing", e, url)
    else:
        try:
            data = bz2.decompress(response)
            datafiles[filename] = pandas.read_csv(io.BytesIO(data))
            print("Successfully decompressed" + filename)
        except Exception as e:
            print("Caught error \"{0}\" at {1}".format(e,url))
    

# <codecell>

print (csvData)

# <codecell>

# get all the machines self-reporting as "Darwin" (Mac OS X)
macs = csvData[csvData['Platform'] == 'darwin']

# get all the machines self-reporting as "Linux2" (Ubuntu)
ubuntus = csvData[csvData['Platform'] == 'linux2']

# now get all nonzero ST_SIZE values from Macs and Ubuntus for graphing

mac_sizes = []
ubuntu_sizes = []

for key, value in datafiles.items():
    if key in list(macs['Filename']):
        mac_sizes = mac_sizes + [size for size in value['st_size'] if size > 1]

for key, value in datafiles.items():
    if key in list(ubuntus['Filename']):
        ubuntu_sizes = ubuntu_sizes + [size for size in value['st_size'] if size > 1]
        
# now get all nonzero ST_SIZE and ST_NLINK values from Macs and Ubuntus for graphing

mac_sizes = []
ubuntu_sizes = []
mac_nlink = []
ubuntu_nlink = []

for key, value in datafiles.items():
    if key in list(macs['Filename']):
        mac_sizes = mac_sizes + [size for size in value['st_size'] if size > 1]
        # NLINK = 1: file, NLINK > 1: directory
        mac_nlink = mac_sizes + [nlink for nlink in value['st_nlink'] if nlink > 1]

for key, value in datafiles.items():
    if key in list(ubuntus['Filename']):
        ubuntu_sizes = ubuntu_sizes + [size for size in value['st_size'] if size > 1]
        ubuntu_nlink = ubuntu_sizes + [nlink for nlink in value['st_nlink'] if nlink > 1]

# <markdowncell>

# Start graphing
# --------------
# 
# Now that we've got our dataset, we can start doing some plotting 

# <codecell>

from scipy import stats
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# make distribution plots for filesize on OSX and Ubuntu (matplotlib style)
bins = 25
plt.hist(ubuntu_sizes, bins, log=True, normed=True, color="#6495ED", alpha=.5, histtype="stepfilled")
plt.hist(mac_sizes, bins, log=True, normed=True, color="#F08080", alpha=.5, histtype="stepfilled");
plt.xlabel('File size')
plt.ylabel('Frequency (logarithmic)')
plt.title('Distribution of file sizes on Ubuntu and Mac OS X')
plt.show()

# <codecell>

# make distribution plots for filesize on OSX and Ubuntu (matplotlib style)
bins = 25
plt.hist(ubuntu_nlink, bins, log=True, normed=True, color="#6495ED", alpha=.5, histtype="stepfilled")
plt.hist(mac_nlink, bins, log=True, normed=True, color="#F08080", alpha=.5, histtype="stepfilled");
plt.xlabel('inode link count')
plt.ylabel('Frequency (logarithmic)')
plt.title('Distribution of inode link density on Ubuntu and Mac OS X')
plt.show()

# <codecell>

sns.distplot(mac_sizes)

# <codecell>


